POST http://localhost:3010/auth/cadastro/
Content-Type: application/json

{
            "name": "teste",
            "surname":"req.body.surname",
            "rg":324234,
            "tel":"4376865",
            "matricula": 1231432,
            "email": "req.body.email",
            "password": "req.body.password",
            "university": "USP"

}